/**
 * Maps each local achievement id (achievementDefs.ts) to the achievement id
 * generated by the Google Play Console when that achievement is created
 * under Play Games Services. Placeholder values until Play Console setup is
 * done — see the Google Play Games plan for the manual console steps.
 *
 * Every id in ACHIEVEMENTS must have an entry here (see playGamesIds.test.ts)
 * so a newly-added achievement can't silently ship without a Play Console
 * counterpart.
 */
export const PLAY_GAMES_ACHIEVEMENT_IDS: Record<string, string> = {
  'first-room': 'PLACEHOLDER_first-room',
  'five-rooms': 'PLACEHOLDER_five-rooms',
  'ten-rooms': 'PLACEHOLDER_ten-rooms',
  'second-floor': 'PLACEHOLDER_second-floor',
  'first-staff': 'PLACEHOLDER_first-staff',
  'earn-1000': 'PLACEHOLDER_earn-1000',
  'earn-10000': 'PLACEHOLDER_earn-10000',
  'earn-100000': 'PLACEHOLDER_earn-100000',
  'first-upgrade': 'PLACEHOLDER_first-upgrade',
  'second-location': 'PLACEHOLDER_second-location',
  'all-locations': 'PLACEHOLDER_all-locations',
  'first-prestige': 'PLACEHOLDER_first-prestige',
  'hire-a-manager': 'PLACEHOLDER_hire-a-manager',
  'wing-expander': 'PLACEHOLDER_wing-expander',
  'wing-master': 'PLACEHOLDER_wing-master',
  'party-goer': 'PLACEHOLDER_party-goer',
  'event-veteran': 'PLACEHOLDER_event-veteran',
  'five-star-streak': 'PLACEHOLDER_five-star-streak',
  'dedicated-owner': 'PLACEHOLDER_dedicated-owner',
  'guest-whisperer': 'PLACEHOLDER_guest-whisperer',
  'loyal-guestkeeper': 'PLACEHOLDER_loyal-guestkeeper',
}

/** The single Play Console leaderboard id for lifetime earnings. */
export const LIFETIME_EARNINGS_LEADERBOARD_ID = 'PLACEHOLDER_lifetime-earnings-leaderboard'
